#!/usr/bin/env python3

from socket     import AF_INET, SOCK_STREAM, socket as Socket
from sys        import argv
from test_dvrip import *

socket = Socket(AF_INET, SOCK_STREAM)
socket.connect((argv[1], 34567))
fp = socket.makefile('rwb')
req = ClientLogin(argv[2], argv[3])
q, = list(req.topackets(MockSession()))
q.dump(fp)
fp.flush()
p = Packet.load(fp)
rep, = req.acceptor().accept(p)
print(rep.result, hex(rep.session))
